
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8
    password: root
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/