eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: false #设置本服务自身是server 不需要注册
#    server:
#      enable-self-preservation: false
      # instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
    application:
        name: eureka
server:
    port: 8761